name: Deploy Docs

on:
  push:
    branches:
      - develop
jobs:
  docs:
    name: Deploy Docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        id: lint
        run: npm run lint
      - name: Build storybook docs
        id: build
        if: steps.lint.outcome == 'success'
        run: npm run build-sb
      - name: Deploy docs
        if: steps.build.outcome == 'success'
        run: |
          npm install
          npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
