name: Publish

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        id: lint
        run: npm run lint
      - name: Make a build
        id: build
        if: steps.lint.outcome == 'success'
        run: npm run build
      - name: Publish to NPM
        if: steps.build.outcome == 'success'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
